defaultContentLanguage = "en"
title = "Open Elements"
baseURL = "https://open-elements.com"

enableRobotsTXT = true
log = true
logFile = "hugo-build.log"
enableGitInfo = true

[languages.en]
weight = 1
languageCode = "en-us"
languageName = "EN"
[languages.en.params]
description = "Open Source made right - Open Elements is a modern company with a clear focus on Open Source and Java"

[languages.de]
weight = 2
languageCode = "de"
languageName = "DE"
[languages.de.params]
description = "Open Source, aber richtig - Open Elements ist ein modernes Unternehmen mit einem Fokus auf Open Source und Java"

[markup.goldmark.renderer]
unsafe = true

[permalinks.page]
posts = '/posts/:year/:month/:day/:slug/'
[permalinks.section]
posts = '/posts'

[outputs]
home = ["HTML", "RSS", "Atom"]
page = ["HTML"]
section = ["HTML", "RSS", "Atom"]

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom+xml"
baseName = "atom"
isPlainText = false

[services.rss]
limit = 20
