[build]
command = "pnpm install && pnpm run build"

[build.environment]
NODE_VERSION = "22"
PNPM_VERSION = "10"

# Production build
[context.production]
command = "pnpm install && pnpm run build"

# Deploy Preview build
[context.deploy-preview]
command = "pnpm install && pnpm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"
