[build]
command = "npm run netlify:build"
publish = "public"

[build.environment]
HUGO_VERSION = "0.134.3"

# Production build
[context.production]
command = "npm run netlify:build:production"

# Deploy Preview build
[context.deploy-preview]
command = "npm run netlify:build:deploy-preview"
